platform :ios, "8.0"
inhibit_all_warnings!

target 'RZImposter', :exclusive => true do
  pod "RZImposter", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "RZImposter", :path => "../"

    pod 'Expecta',		'~>0.3.1'
    pod 'AFNetworking', '~>2.5.3'
end
